### PR TITLE
Storybook

### PR DESCRIPTION
**Pull request by fostergn**
- adding storybook to project
- adding widget to stories index.js

storybook

### CODE REVIEW

**Comment by seriousben** [comment]
Would it be possible to find a way to expose the stories in the dist? Would be awesome to link to it from the demo page.

**Comment by fostergn** [comment]
@seriousben we could just push master's storybook build to a github pages thing if you want a prod build of it to live somewhere

**Comment by fostergn** [comment]
@seriousben I added a `deploy-storybook` command that will publish the storybook build to github pages. you can see an example from my forked repo https://fostergn.github.io/embeddable-react-widget/?path=/story/widget--default

**Comment by fostergn** [comment]
@seriousben added storybook to output in the dist folder and linked to it in the index.html

**Comment by seriousben** [comment]
Thanks for your contribution :) this is great

**Pull request merged**
